# Generated by Django 5.1.4 on 2025-01-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebPageFTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'webpage_fts',
                'managed': False,
            },
        ),
    ]
