# Generated by Django 5.1.4 on 2025-01-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PST', '0003_visitedurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
