# Generated by Django 5.1.4 on 2025-01-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PST', '0004_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='tfidf_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
